import { mkdir, writeFile, access } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.resolve(__dirname, "..");
const outputRoot = path.join(projectRoot, "generated");

function sanitizeProjectName(input) {
  return input.trim().toLowerCase().replace(/[^a-z0-9-_]+/g, "-");
}

function buildPackageJson(projectName) {
  return JSON.stringify(
    {
      name: projectName,
      version: "0.1.0",
      private: true,
      type: "module",
      scripts: {
        start: "node src/index.js"
      }
    },
    null,
    2
  );
}

function buildReadme(projectName) {
  return `# ${projectName}

Minimal MCP project generated by MCP_creator.

## Start

\`\`\`bash
npm start
\`\`\`
`;
}

function buildServerFile(projectName) {
  return `const appName = "${projectName}";

console.log(\`MCP project "\${appName}" is ready.\`);
console.log("Next step: replace this file with your MCP server implementation.");
`;
}

async function exists(targetPath) {
  try {
    await access(targetPath);
    return true;
  } catch {
    return false;
  }
}

async function createProject(rawName) {
  if (!rawName) {
    console.error("Usage: node src/index.js <project-name>");
    process.exitCode = 1;
    return;
  }

  const projectName = sanitizeProjectName(rawName);

  if (!projectName) {
    console.error("Project name is invalid.");
    process.exitCode = 1;
    return;
  }

  const targetRoot = path.join(outputRoot, projectName);
  const targetSrc = path.join(targetRoot, "src");

  if (await exists(targetRoot)) {
    console.error(`Project already exists: ${targetRoot}`);
    process.exitCode = 1;
    return;
  }

  await mkdir(targetSrc, { recursive: true });
  await writeFile(path.join(targetRoot, "package.json"), buildPackageJson(projectName));
  await writeFile(path.join(targetRoot, "README.md"), buildReadme(projectName));
  await writeFile(path.join(targetSrc, "index.js"), buildServerFile(projectName));

  console.log(`Project created in ${targetRoot}`);
}

createProject(process.argv[2]);
